#define WIFI_SSID "YOUR WIFI SSID"
#define WIFI_PASSWORD "YOUR WIFI PASSWORD"

#define KENSHI_TASK_ID "YOUR KENSHI TASK ID"
#define KENSHI_API_KEY "YOUR KENSHI MQL API KEY"
#define KENSHI_API_OWNER "OWNER ADDRESS OF YOUR KENSHI MQL API KEY"

#define RED_LED_PIN 16
#define GREEN_LED_PIN 17
